import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Next JS ver.13</title>
      </head>
      <body className={inter.className}>
        <nav className="flex sm:justify-center space-x-4 h-12">
          {[
            ["Home", "/main"],
            ["Mypage", "/mypage"],
          ].map(([title, url], i) => (
            <a
              key={i}
              href={url}
              className="rounded-lg px-3 py-2 text-slate-700 font-medium hover:bg-slate-100 hover:text-slate-900"
            >
              {title}
            </a>
          ))}
        </nav>
        {children}
      </body>
    </html>
  );
}
